### ISSUE TITLE
Vein Mining enchantment cannot be applied to Jeweler's Hammer

### ISSUE THREAD

**Issue by abilliontrillionstars** [ChloeTax/Hexxytest#17] opened 2024-07-09 04:41 UTC
Vein Mining will not appear in the applicable enchantments EMI submenu for uses of the hammer, and a book with the enchant cannot be applied to the hammer in an anvil.

**Comment by ChloeTax** [comment] 2024-07-09 12:36
duplicate of https://github.com/ChloeTax/Hexxytest/issues/10

**Closed as completed by ChloeTax** 2024-07-09 12:36 UTC
Labels: duplicate
